### ISSUE TITLE
[8.0] ir_export_extended_ept - OCA

### ISSUE THREAD

**Issue by rafaelbn** [emiprotechnologies/odoo-addons#1]
Hi @emiprotechnologies ,

Some of your modules looks very useful, Would you like yo add them to OCA?

There you will have revisions for improving them and more visibility of you work.

Let me know

Thanks
Regards

**Comment by emiprotechnologies** [comment]
Hi @rafaelbn ,

We want to add our useful addons to OCA.

**Comment by rafaelbn** [comment]
Hi @emiprotechnologies ,

We can move this module to OCA for you (you will of course maintain authoring) and in the process @antespi will show you howto. OK?

We have done something similar and we would like to add more functionality:

https://github.com/Antiun/antiun-odoo-addons/tree/8.0/base_exports_manager

Please let me know if you are agree and we will proceed

Thanks
Regards

**Comment by emiprotechnologies** [comment]
Hi @rafaelbn ,

If we want to do it our self then How can we do ?

Can you guide us to do this ?

In future we will also contribute more addons in OCA.

Please guide you or tell @antespi for guide us.

Thanks
Regards

**Comment by rafaelbn** [comment]
Hi @emiprotechnologies ,

First you have to sign CLA: https://odoo-community.org/page/cla

After this you have to read here https://odoo-community.org/page/Contribute

And change you module to fit this template: https://github.com/OCA/maintainer-tools/tree/master/template/module

Please let me know if you have any doubt.

Thanks
Regards

**Comment by emiprotechnologies** [comment]
Hi @rafaelbn ,

We have already sign CLA. You can see our contribution.

And going to changes according to given template.

After changes what we have to do ?

Thanks
Regards

**Comment by rafaelbn** [comment]
Hi @emiprotechnologies ,

If you have already contributed to OCA you just have to make in OCA the PR as you did before in the repository https://github.com/OCA/web, then Contributors will review you module and you will have to make fixes or improvement to be merged.

Inside OCA nobody has repositories, all are community and managed by OCA board.

**Comment by emiprotechnologies** [comment]
Hi @rafaelbn ,

I got an email as like below.

 Chirag Rajkotiya,

You have been invited to connect to "Odoo Community Association (OCA)" in order to get access to your documents in OpenERP.

To accept the invitation, click on the following link:

Thanks,

--
Odoo Community Association (OCA)
info@odoo-community.org

May I know what is it ?

How can I use this account ?

Thanks for your help
Regards.

**Comment by rafaelbn** [comment]
Hi @emiprotechnologies ,

> We have already sign CLA. You can see our contribution.

How did you make the PRs in your other contributions?

> I got an email as like below.
Chirag Rajkotiya,
You have been invited to connect to "Odoo Community Association (OCA)" in order to get access to your documents in OpenERP.
To accept the invitation, click on the following link:

I you got this e-mail is because you have registered in OCA

> May I know what is it ?
How can I use this account ?

This is you access to de OCA's Odoo, you have to login and there you will receive information.

**Comment by emiprotechnologies** [comment]
Hi @rafaelbn ,

Thanks for giving information.

From my login I can not set my github account from User=>Preferences.

Can you help me on this ?

Thanks
Regards

**Comment by rafaelbn** [comment]
Please send full screen-shots to see where are you trying to do this.

**Comment by emiprotechnologies** [comment]
Hi @rafaelbn ,

Please have a look on the following images.

![screenshot from 2015-09-22 16 11 40](https://cloud.githubusercontent.com/assets/10369865/10016483/f9cc4e0e-6144-11e5-8ec7-f30e182075b3.png)

I want to set github account.

But it gives me message as like below.

![screenshot from 2015-09-22 16 11 54](https://cloud.githubusercontent.com/assets/10369865/10016471/eeae4d06-6144-11e5-9e69-1c7206d87711.png)

**Comment by jgrandguillaume** [comment]
Hi there,


I think it should be ok by now @emiprotechnologies . Checking in the OCA instance, I see that your github login is alright 

![selection_293](https://cloud.githubusercontent.com/assets/151794/10040039/62933112-61d8-11e5-86fc-98d54ed5142c.jpg)

Thanks for contributing to OCA

Best regards,

Joël

**Comment by rafaelbn** [comment]
Hi @emiprotechnologies is all clear?

You can check How to create a PR to OCA here: https://gist.github.com/JavierIniesta/f6eb28d19237c695e440

**Comment by rafaelbn** [comment]
Hi @emiprotechnologies ,

@jgrandguillaume fix your issue in OCA and we, Antiun did a how to here: https://gist.github.com/JavierIniesta/f6eb28d19237c695e440

Let me know if you are interested in porting this module to OCA please

Thanks
Regards,
Rafael

**Comment by rafaelbn** [comment]
Closing this issue, we will make a new module in OCA for improve exports
